import = [
    "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
]

live_config_reload = true

[shell]
program = "/usr/bin/fish"

[cursor]
style = {blinking = "On", shape = "Block"}

[env]
TERM = "xterm-256color"

[font]
size = 14

[font.normal]
family = "Hack Nerd Font Mono"
style = "Regular"

[scrolling]
history = 100000

[window]
dynamic_title = true
title = "Terminal"
padding.x = 10
padding.y = 10
decorations = "Buttonless"
opacity = 0.9
blur = true
