;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;
;==========================================================

[colors]
bg_dim = #141617
bg0 = #1d2021
bg1 = #282828
bg2 = #282828
bg3 = #3c3836
bg4 = #3c3836
bg5 = #504945
bg_statusline1 = #282828
bg_statusline2 = #32302f
bg_statusline3 = #504945
bg_diff_green = #32361a
bg_visual_green = #333e34
bg_diff_red = #3c1f1e
bg_visual_red = #442e2d
bg_diff_blue = #0d3138
bg_visual_blue = #2e3b3b
bg_visual_yellow = #473c29
bg_current_word = #32302f
fg0 = #d4be98
fg1 = #ddc7a1
red = #ea6962
orange = #e78a4e
yellow = #d8a657
green = #a9b665
aqua = #89b482
blue = #7daea3
purple = #d3869b
bg_red = #ea6962
bg_green = #a9b665
bg_yellow = #d8a657
grey0 = #7c6f64
grey1 = #928374
grey2 = #a89984

[bar/default]
width = 100%
height = 16pt
radius = 0

dpi = 0

background = ${colors.bg_dim}
foreground = ${colors.fg0}

line-size = 3pt

border-size = 0pt
border-color = #00000000

padding-left = 0
padding-right = 1

module-margin = 1

separator = |
separator-foreground = ${colors.bg_statusline3}

font-0 = OverpassNerdFontPropo:size=8;3
locale = sv_SE.UTF-8

modules-left = network-networkmanager tray
modules-center = i3
modules-right = player-mpris-tail pulseaudio date

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

wm-restack = i3

override-redirect = true

[module/i3]
type = internal/i3
pin-workspaces = true
show-urgent = true
strip-wsnumbers = true
enable-click = true
enable-scroll = true
wrapping-scroll = true

;label-separator = |

label-mode = %mode%
label-mode-padding = 2
label-mode-background = ${colors.bg_red}

label-focused = %name%
label-focused-underline = ${colors.bg_red}
label-focused-padding = 2

label-unfocused = %name%
label-unfocused-padding = 2

label-urgent = %index%: %name%
label-urgent-background = ${colors.bg_red}
label-urgent-padding = 2

[module/info-camera-mic]
type = custom/script
exec = ~/.config/polybar/scripts/info-camera-mic.sh
interval = 5

[module/player-mpris-tail]
type = custom/script
exec = ~/.config/polybar/scripts/player-mpris-tail.py -f '{icon} {artist} - {title}'
tail = true

[module/tray]
type = internal/tray

format-margin = 8pt
tray-spacing = 16pt

[module/xwindow]
type = internal/xwindow
label = %title:0:60:...%

[module/pulseaudio]
type = internal/pulseaudio

format-volume-prefix = "VOL "
format-volume = <label-volume>

label-volume = %percentage%%

label-muted = muted
label-muted-foreground = ${colors.grey0}

[module/network-networkmanager]
type = custom/script
exec = ~/.config/polybar/scripts/network-networkmanager.sh
tail = true

[module/date]
type = internal/date
interval = 60

date = %Y-%m-%d %H:%M

label = %date%

[settings]
screenchange-reload = true
pseudo-transparency = true

; vim:ft=dosini
