#!/usr/bin/sh
MAS=$(amixer get Master  | grep 'Mono')

M_MUTE=$(echo $MAS | awk -F '[][]' '{ print $6 }')

M_VOL=$(echo $MAS | awk -F '[][]' '{ print $2 }')


if [ $M_MUTE == "on" ]
then
   M_MUTE="unmuted"
else
   M_MUTE="muted"
fi
   
rofi -theme output -e "$M_MUTE $M_VOL"
